# Generated by Django 3.2 on 2023-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analog',
            old_name='marking_original',
            new_name='marking',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='num_wires',
            field=models.IntegerField(),
        ),
    ]
