# Generated by Django 3.2 on 2023-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_auto_20230111_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog',
        ),
        migrations.AddField(
            model_name='analog',
            name='marking_analog',
            field=models.ManyToManyField(to='parsing.Sensor'),
        ),
    ]
