# Generated by Django 3.2 on 2023-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20230112_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog',
        ),
        migrations.AddField(
            model_name='analog',
            name='marking_analog',
            field=models.ManyToManyField(to='parsing.Sensor'),
        ),
    ]
