# Generated by Django 3.2 on 2023-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_auto_20230117_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='diameter',
            new_name='connector',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='sensing_urface',
            new_name='ground',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensing_surface',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='standard_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
