# Generated by Django 3.2 on 2023-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0009_auto_20230123_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='class_temp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
