# Generated by Django 3.2 on 2023-01-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_auto_20230126_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='analog',
            name='difference3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analog',
            name='difference4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='manufacture_original',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
