# Generated by Django 3.2 on 2023-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0014_auto_20230131_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analog',
            name='list_analog',
        ),
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog1',
        ),
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog2',
        ),
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog3',
        ),
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog4',
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='manufacture_original',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='analog',
            name='marking_analog',
        ),
        migrations.AddField(
            model_name='analog',
            name='marking_analog',
            field=models.ManyToManyField(to='parsing.Sensor'),
        ),
    ]
