# Generated by Django 3.2 on 2023-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0015_auto_20230131_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analog',
            name='difference',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference1',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference2',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference3',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference4',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
