# Generated by Django 3.2 on 2023-01-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0017_auto_20230131_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='analog',
            name='mark',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='analog',
            name='mark1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='analog',
            name='mark2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='analog',
            name='mark3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='analog',
            name='mark4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analog',
            name='difference4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
